[package]
org = "ballerinax"
name = "davincipas201"
version = "1.0.0"
distribution = "2201.8.1"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "davincipas201"]
export = ["davincipas201"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "5.0.0"